services:
  backend:
    build: .
    container_name: django-docker
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/db
    command: python "Start Website First Time.py"

  worker:
    build: .
    container_name: huey-worker-docker
    volumes:
      - .:/app
      - sqlite_data:/app/db
    command: sh -c "sleep 15 && python manage.py run_huey"

volumes:
  sqlite_data: