services:
  backend:
    build: .
    container_name: django-docker
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8000"
    env_file:
      - .env
    command: python "Start Website First Time.py"

  worker:
    build: .
    command: python manage.py run_huey
    container_name: huey-worker-docker
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    container_name: database-docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT_HOST}:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 3s
      retries: 30
