services:
  backend:
    build: 
      context: .
      dockerfile: dockerfile.backend
    port:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database

  worker:
    build: .
    command: python manage.py run_huey
    depends_on:
      - backend

  frontend:
    build: .
    command: python manage.py tailwind build
    depends_on:
      - backend

  database:
    image: postgres:17
    environment:
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_DB: ${DB_NAME}
      - port : ${DB_PORT}